import { useState } from "react";
import { motion } from "motion/react";
import {
  FileText,
  Download,
  CheckCircle2,
  Clock,
  AlertTriangle,
  AlertCircle,
  MailCheck,
} from "lucide-react";
import { sendEmailVerification } from "firebase/auth";
import { auth } from "../../Firebase/firebase";
import { Card, CardContent, CardHeader, CardTitle } from "../../app/components/ui/card";
import { Badge } from "../../app/components/ui/badge";
import { Button } from "../../app/components/ui/button";
import { Separator } from "../../app/components/ui/separator";
import { Skeleton } from "../../app/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../../app/components/ui/table";
import { useClientInvoices } from "../hooks/useClientInvoices";
import type { ClientInvoice, InvoiceStatus } from "../lib/invoices";

const inr = (value: number) => `₹${value.toLocaleString("en-IN")}`;

const invoiceDateFormatter = new Intl.DateTimeFormat("en-US", {
  year: "numeric",
  month: "short",
  day: "numeric",
  timeZone: "UTC",
});

function formatInvoiceDate(date: Date | null): string {
  return date ? invoiceDateFormatter.format(date) : "—";
}

function invoiceStatusBadge(status: InvoiceStatus) {
  switch (status) {
    case "paid":
      return (
        <Badge className="bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-950/50 dark:text-emerald-400 dark:border-emerald-800">
          <CheckCircle2 className="h-3 w-3 mr-1" />
          Paid
        </Badge>
      );
    case "unpaid":
      return (
        <Badge className="bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-950/50 dark:text-amber-400 dark:border-amber-800">
          <Clock className="h-3 w-3 mr-1" />
          Unpaid
        </Badge>
      );
    default:
      return (
        <Badge variant="destructive">
          <AlertTriangle className="h-3 w-3 mr-1" />
          Overdue
        </Badge>
      );
  }
}

function PageTitle() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
    >
      <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
        Invoices
      </h1>
      <p className="text-gray-500 dark:text-gray-400 mt-1">
        View and download invoices for your project.
      </p>
    </motion.div>
  );
}

function handleDownload(invoice: ClientInvoice) {
  const lines = [
    `INVOICE: ${invoice.number}`,
    `Date: ${formatInvoiceDate(invoice.date)}`,
    `Due Date: ${formatInvoiceDate(invoice.dueDate)}`,
    `Status: ${invoice.status.toUpperCase()}`,
    "",
    "ITEMS:",
    ...invoice.items.map(
      (item) => `  ${item.description} — ${inr(item.amount)}`,
    ),
    "",
    `TOTAL: ${inr(invoice.total)}`,
    "",
    "Generated by Servio",
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${invoice.number}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function InvoiceManagement() {
  const { invoices, loading, error, needsEmailVerification } =
    useClientInvoices();
  const [resending, setResending] = useState(false);
  const [resent, setResent] = useState(false);

  async function handleResendVerification() {
    if (!auth.currentUser) return;
    setResending(true);
    try {
      await sendEmailVerification(auth.currentUser);
      setResent(true);
    } catch {
      /* allow the user to try again */
    } finally {
      setResending(false);
    }
  }

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-56" />
        <div className="space-y-4">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-40" />
          ))}
        </div>
      </div>
    );
  }

  if (needsEmailVerification) {
    return (
      <div className="space-y-6">
        <PageTitle />
        <div className="flex flex-col items-center py-16 text-center">
          <MailCheck className="h-12 w-12 text-indigo-300 dark:text-indigo-500/70 mb-4" />
          <p className="text-gray-700 dark:text-gray-200 font-medium">
            Verify your email to see your invoices
          </p>
          <p className="mt-1 max-w-sm text-sm text-gray-500 dark:text-gray-400">
            Invoices are tied to your verified email. Check your inbox for the
            verification link, then refresh this page.
          </p>
          {resent ? (
            <p className="mt-4 text-sm text-emerald-600 dark:text-emerald-400">
              Verification email sent — check your inbox.
            </p>
          ) : (
            <button
              type="button"
              onClick={handleResendVerification}
              disabled={resending}
              className="mt-4 rounded-lg bg-gradient-to-r from-indigo-600 to-purple-600 px-4 py-2 text-sm font-medium text-white shadow-sm transition-all hover:shadow-md focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 disabled:opacity-60"
            >
              {resending ? "Sending…" : "Resend verification email"}
            </button>
          )}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="space-y-6">
        <PageTitle />
        <div role="alert" className="flex flex-col items-center py-16 text-center">
          <AlertCircle className="h-12 w-12 text-red-300 dark:text-red-500/70 mb-4" />
          <p className="text-gray-700 dark:text-gray-200 font-medium">
            We couldn&apos;t load your invoices
          </p>
          <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
            Please check your connection and try again in a moment.
          </p>
        </div>
      </div>
    );
  }

  if (invoices.length === 0) {
    return (
      <div className="space-y-6">
        <PageTitle />
        <div className="flex flex-col items-center py-16 text-center">
          <FileText className="h-12 w-12 text-gray-300 dark:text-gray-600 mb-4" />
          <p className="text-gray-700 dark:text-gray-200 font-medium">
            No invoices yet
          </p>
          <p className="mt-1 max-w-sm text-sm text-gray-500 dark:text-gray-400">
            When your team issues an invoice for your project, it&apos;ll appear
            here.
          </p>
        </div>
      </div>
    );
  }

  const paidCount = invoices.filter((i) => i.status === "paid").length;
  const outstandingCount = invoices.length - paidCount;

  return (
    <div className="space-y-6">
      <PageTitle />

      {/* Summary row */}
      <div className="grid gap-4 sm:grid-cols-3">
        {[
          {
            label: "Total Invoices",
            value: invoices.length.toString(),
            color: "text-gray-900 dark:text-gray-100",
          },
          {
            label: "Paid",
            value: paidCount.toString(),
            color: "text-emerald-600 dark:text-emerald-400",
          },
          {
            label: "Outstanding",
            value: outstandingCount.toString(),
            color: "text-amber-600 dark:text-amber-400",
          },
        ].map((item, idx) => (
          <motion.div
            key={item.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: idx * 0.08 }}
          >
            <Card className="border-gray-200 dark:border-slate-800 bg-white dark:bg-slate-900">
              <CardContent className="pt-6 text-center">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  {item.label}
                </p>
                <p className={`text-3xl font-bold mt-1 ${item.color}`}>
                  {item.value}
                </p>
              </CardContent>
            </Card>
          </motion.div>
        ))}
      </div>

      <Separator />

      {/* Invoice cards */}
      <div className="space-y-4">
        {invoices.map((invoice, idx) => (
          <motion.div
            key={invoice.id}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: idx * 0.06 }}
          >
            <Card className="border-gray-200 dark:border-slate-800 bg-white dark:bg-slate-900">
              <CardHeader>
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <div className="flex items-center gap-3">
                    <div className="rounded-lg p-2 bg-indigo-50 dark:bg-indigo-950/50">
                      <FileText className="h-4 w-4 text-indigo-500" />
                    </div>
                    <div>
                      <CardTitle className="text-base font-semibold text-gray-900 dark:text-gray-100">
                        {invoice.number}
                      </CardTitle>
                      <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                        Issued: {formatInvoiceDate(invoice.date)} · Due:{" "}
                        {formatInvoiceDate(invoice.dueDate)}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {invoiceStatusBadge(invoice.status)}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownload(invoice)}
                      className="gap-1"
                    >
                      <Download className="h-3.5 w-3.5" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                {invoice.items.length === 0 ? (
                  <p className="text-sm text-gray-500 dark:text-gray-400 text-center py-4">
                    No line items.
                  </p>
                ) : (
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Description</TableHead>
                        <TableHead className="text-right">Amount</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {invoice.items.map((item, i) => (
                        <TableRow key={i}>
                          <TableCell className="text-gray-600 dark:text-gray-300">
                            {item.description || "—"}
                          </TableCell>
                          <TableCell className="text-right font-medium text-gray-900 dark:text-gray-100">
                            {inr(item.amount)}
                          </TableCell>
                        </TableRow>
                      ))}
                      <TableRow>
                        <TableCell className="font-semibold text-gray-900 dark:text-gray-100">
                          Total
                        </TableCell>
                        <TableCell className="text-right font-bold text-gray-900 dark:text-gray-100">
                          {inr(invoice.total)}
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                )}
              </CardContent>
            </Card>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
