import { motion } from "motion/react";
import {
  FileText,
  Download,
  CheckCircle2,
  Clock,
  AlertTriangle,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "../../app/components/ui/card";
import { Badge } from "../../app/components/ui/badge";
import { Button } from "../../app/components/ui/button";
import { Separator } from "../../app/components/ui/separator";
import { Skeleton } from "../../app/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../../app/components/ui/table";
import { useProjects } from "../hooks/useProjects";
import type { Invoice } from "../types";

function invoiceStatusBadge(status: Invoice["status"]) {
  switch (status) {
    case "paid":
      return (
        <Badge className="bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-950/50 dark:text-emerald-400 dark:border-emerald-800">
          <CheckCircle2 className="h-3 w-3 mr-1" />
          Paid
        </Badge>
      );
    case "unpaid":
      return (
        <Badge className="bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-950/50 dark:text-amber-400 dark:border-amber-800">
          <Clock className="h-3 w-3 mr-1" />
          Unpaid
        </Badge>
      );
    default:
      return (
        <Badge variant="destructive">
          <AlertTriangle className="h-3 w-3 mr-1" />
          Overdue
        </Badge>
      );
  }
}

export function InvoiceManagement() {
  const { projects, loading } = useProjects();

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-8 w-56" />
        <div className="space-y-4">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-40" />
          ))}
        </div>
      </div>
    );
  }

  const project = projects[0];
  if (!project) return null;

  const handleDownload = (invoice: Invoice) => {
    const lines = [
      `INVOICE: ${invoice.number}`,
      `Date: ${invoice.date}`,
      `Due Date: ${invoice.dueDate}`,
      `Status: ${invoice.status.toUpperCase()}`,
      "",
      "ITEMS:",
      ...invoice.items.map(
        (item) =>
          `  ${item.description} — ₹${item.amount.toLocaleString("en-IN")}`,
      ),
      "",
      `TOTAL: ₹${invoice.amount.toLocaleString("en-IN")}`,
      "",
      "Project: " + project.name,
      "Generated by Servio",
    ];

    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${invoice.number}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
      >
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
          Invoices
        </h1>
        <p className="text-gray-500 dark:text-gray-400 mt-1">
          View and download invoices for{" "}
          <span className="font-medium">{project.name}</span>
        </p>
      </motion.div>

      {/* Summary row */}
      <div className="grid gap-4 sm:grid-cols-3">
        {[
          {
            label: "Total Invoices",
            value: project.invoices.length.toString(),
            color: "text-gray-900 dark:text-gray-100",
          },
          {
            label: "Paid",
            value: project.invoices
              .filter((i) => i.status === "paid")
              .length.toString(),
            color: "text-emerald-600 dark:text-emerald-400",
          },
          {
            label: "Outstanding",
            value: project.invoices
              .filter((i) => i.status !== "paid")
              .length.toString(),
            color: "text-amber-600 dark:text-amber-400",
          },
        ].map((item, idx) => (
          <motion.div
            key={item.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: idx * 0.08 }}
          >
            <Card className="border-gray-200 dark:border-slate-800 bg-white dark:bg-slate-900">
              <CardContent className="pt-6 text-center">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  {item.label}
                </p>
                <p className={`text-3xl font-bold mt-1 ${item.color}`}>
                  {item.value}
                </p>
              </CardContent>
            </Card>
          </motion.div>
        ))}
      </div>

      <Separator />

      {/* Invoice cards */}
      <div className="space-y-4">
        {project.invoices.map((invoice, idx) => (
          <motion.div
            key={invoice.id}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: idx * 0.06 }}
          >
            <Card className="border-gray-200 dark:border-slate-800 bg-white dark:bg-slate-900">
              <CardHeader>
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <div className="flex items-center gap-3">
                    <div className="rounded-lg p-2 bg-indigo-50 dark:bg-indigo-950/50">
                      <FileText className="h-4 w-4 text-indigo-500" />
                    </div>
                    <div>
                      <CardTitle className="text-base font-semibold text-gray-900 dark:text-gray-100">
                        {invoice.number}
                      </CardTitle>
                      <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                        Issued: {invoice.date} · Due: {invoice.dueDate}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {invoiceStatusBadge(invoice.status)}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownload(invoice)}
                      className="gap-1"
                    >
                      <Download className="h-3.5 w-3.5" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Description</TableHead>
                      <TableHead className="text-right">Amount</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {invoice.items.map((item, i) => (
                      <TableRow key={i}>
                        <TableCell className="text-gray-600 dark:text-gray-300">
                          {item.description}
                        </TableCell>
                        <TableCell className="text-right font-medium text-gray-900 dark:text-gray-100">
                          ₹{item.amount.toLocaleString("en-IN")}
                        </TableCell>
                      </TableRow>
                    ))}
                    <TableRow>
                      <TableCell className="font-semibold text-gray-900 dark:text-gray-100">
                        Total
                      </TableCell>
                      <TableCell className="text-right font-bold text-gray-900 dark:text-gray-100">
                        ₹{invoice.amount.toLocaleString("en-IN")}
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
            </Card>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
